### ISSUE TITLE
Regarding the issue of the LED not lighting up.

### ISSUE THREAD

**Issue by ijnekenamay** [TOILmodular/Plaits#1]
First of all, the work you are doing is excellent. Thank you for everything you do.

I have assembled the Plaits you have designed and I am very happy with the results. However, all the LEDs do not light up.
I tried to find the cause and noticed that the 0.1uF capacitor near the LED driver and the silk of the BLM18RFerrite Bead are reversed. 
![image](https://github.com/TOILmodular/Plaits/assets/80657332/8fa9b296-64cd-4586-bc2b-ee7234ba94db)

Ignoring the indication on the silk, I replaced the components and it worked fine.
I am writing this in case anyone else is having trouble.
Thanks.

**Comment by TOILmodular** [comment]
Thanks so much for your feedback. Terribly sorry about the mistake. I only realized it because of your issue report, since I did not use the Thank version myself. Fixed now.
It's also good to hear that you can use the Gerber files without problems. I was never sure, if that works well for others.
Hope you have much fun with the module.
